use_frameworks!

platform :ios, '10.0'

target 'rapidsnark_Example' do
  use_frameworks!

  pod 'rapidsnark', :path => '../'

  target 'rapidsnark_Tests' do
    inherit! :search_paths

    
  end
end
